### ISSUE TITLE
1.9.0 - issue with Titanium Backup 6.2.0 receivers

### ISSUE THREAD

**Issue by mag01** [miracle2k/android-autostarts#14]
Hello,
Titanium Backup 6.2.0 contains the following receivers:

pm dump 'com.keramidas.TitaniumBackup'

```
...
  Receiver Resolver Table:
    Full MIME Types:
        application/vnd.wap.mms-message:
          2c724d3a com.keramidas.TitaniumBackup/.apiBackupRestore.DummyReceiver filter 34773401
            Action: "android.provider.Telephony.WAP_PUSH_DELIVER"
            Type: "application/vnd.wap.mms-message"

    Base MIME Types:
        application:
          2c724d3a com.keramidas.TitaniumBackup/.apiBackupRestore.DummyReceiver filter 34773401
            Action: "android.provider.Telephony.WAP_PUSH_DELIVER"
            Type: "application/vnd.wap.mms-message"

    Schemes:
        package:
          350ebdeb com.keramidas.TitaniumBackup/.schedules.BootReceiver filter bf8d485
            Action: "android.intent.action.PACKAGE_REPLACED"
            Scheme: "package"
            Path: "PatternMatcher{LITERAL: com.keramidas.TitaniumBackup}"
          23e6a748 com.keramidas.TitaniumBackup/.PackageEventsReceiver filter d9132da
            Action: "android.intent.action.PACKAGE_ADDED"
            Action: "android.intent.action.PACKAGE_REMOVED"
            Action: "android.intent.action.PACKAGE_CHANGED"
            Scheme: "package"

    Non-Data Actions:
        android.intent.action.EXTERNAL_APPLICATIONS_UNAVAILABLE:
          350ebdeb com.keramidas.TitaniumBackup/.schedules.BootReceiver filter 1ad695fc
            Action: "android.intent.action.BOOT_COMPLETED"
            Action: "android.intent.action.EXTERNAL_APPLICATIONS_AVAILABLE"
            Action: "android.intent.action.EXTERNAL_APPLICATIONS_UNAVAILABLE"
        android.intent.action.EXTERNAL_APPLICATIONS_AVAILABLE:
          350ebdeb com.keramidas.TitaniumBackup/.schedules.BootReceiver filter 1ad695fc
            Action: "android.intent.action.BOOT_COMPLETED"
            Action: "android.intent.action.EXTERNAL_APPLICATIONS_AVAILABLE"
            Action: "android.intent.action.EXTERNAL_APPLICATIONS_UNAVAILABLE"
        android.provider.Telephony.SMS_DELIVER:
          39dd59e1 com.keramidas.TitaniumBackup/.apiBackupRestore.DummyReceiver filter 1ef515e8
            Action: "android.provider.Telephony.SMS_DELIVER"
        com.keramidas.intent.action.SCHEDULE_NEXT_WAKE_UP:
          39a80306 com.keramidas.TitaniumBackup/.schedules.WakeUpReceiver filter 32ed430b
            Action: "com.keramidas.intent.action.SCHEDULE_NEXT_WAKE_UP"
        android.intent.action.BOOT_COMPLETED:
          350ebdeb com.keramidas.TitaniumBackup/.schedules.BootReceiver filter 1ad695fc
            Action: "android.intent.action.BOOT_COMPLETED"
            Action: "android.intent.action.EXTERNAL_APPLICATIONS_AVAILABLE"
            Action: "android.intent.action.EXTERNAL_APPLICATIONS_UNAVAILABLE"
        android.appwidget.action.APPWIDGET_UPDATE:
          1a194dc7 com.keramidas.TitaniumBackup/.MyWidget filter 7b267ce
            Action: "android.appwidget.action.APPWIDGET_UPDATE"
          162eff4 com.keramidas.TitaniumBackup/.MyDataProfileWidget filter 39eb26ef
            Action: "android.appwidget.action.APPWIDGET_UPDATE"

    MIME Typed Actions:
        android.provider.Telephony.WAP_PUSH_DELIVER:
          2c724d3a com.keramidas.TitaniumBackup/.apiBackupRestore.DummyReceiver filter 34773401
            Action: "android.provider.Telephony.WAP_PUSH_DELIVER"
            Type: "application/vnd.wap.mms-message"
```

So there's one receiver for android.intent.action.BOOT_COMPLETED: "com.keramidas.TitaniumBackup/.schedules.BootReceiver"

Autostarts displays the Titanium Backup entry in "After Startup" as "com.keramidas.TitaniumBackup" and when showing its details it displays receiver name as "(no-name)" and is also unable to work with it properly because it tries to perform any operations on "'com.keramidas.TitaniumBackup/(no-name)'" which of course doesn't exist.

When I disable this receiver manually (in shell), then the state in Autostarts still doesn't show it's disabled (even after reload, or relaunch of Autostarts)

Similar issue affects other actions where Titanium Backup appears such as "Application Installed" (android.intent.action.PACKAGE_ADDED) etc.
